# Generated by Django 5.0.3 on 2024-03-24 20:03

import app_billetera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_billetera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="balance",
            field=app_billetera.models.MoneyField(default="0.00"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="change",
            field=app_billetera.models.MoneyField(default="0.00"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="date_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
