# Generated by Django 5.0.3 on 2024-03-24 22:22

import app_billetera.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_billetera", "0002_cliente_balance_cliente_change_cliente_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="balance",
            field=app_billetera.models.MoneyField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="change",
            field=app_billetera.models.MoneyField(default=0.0),
        ),
    ]
