# Generated by Django 5.0.3 on 2024-04-10 16:42

import app_billetera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_billetera", "0003_alter_cliente_balance_alter_cliente_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=80)),
                ("destiny", models.CharField(max_length=80)),
                ("change", app_billetera.models.MoneyField(default=0)),
                ("date_of_change", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="change",
        ),
    ]
