# Generated by Django 5.0.3 on 2024-04-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_billetera", "0004_historial_remove_cliente_change"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historial",
            name="date_of_change",
        ),
    ]
