# Generated by Django 5.0.3 on 2024-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_billetera", "0006_rename_destiny_historial_destino_del_dinero"),
    ]

    operations = [
        migrations.AddField(
            model_name="historial",
            name="date_time_form",
            field=models.DateTimeField(null=True),
        ),
    ]
