# Generated by Django 5.0.3 on 2024-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_billetera', '0007_historial_date_time_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='historial',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
