# Generated by Django 5.0.3 on 2024-06-02 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_billetera", "0008_alter_cliente_balance_alter_historial_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="change",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
